version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/notes?schema=public"
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: "http://localhost:3000"
    ports:
      - "5173:80"

volumes:
  db-data:
